// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmP4xDUUVgA0V6XXdHFcCU7nhyPjBjsSI',
    appId: '1:75826378780:web:6c6c2d8e8c57c6a89f07d9',
    messagingSenderId: '75826378780',
    projectId: 'mybereal-f03e7',
    authDomain: 'mybereal-f03e7.firebaseapp.com',
    databaseURL: 'https://mybereal-f03e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybereal-f03e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0Qk8bJpICD9tvtE5j3uCydXNjWxglXo',
    appId: '1:75826378780:android:b5a4e96f9baf1ae89f07d9',
    messagingSenderId: '75826378780',
    projectId: 'mybereal-f03e7',
    databaseURL: 'https://mybereal-f03e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybereal-f03e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_AVcOdnTSgzDm5EqYkEs1DtWEbpI9J8',
    appId: '1:75826378780:ios:69e5ecefaf1f02ac9f07d9',
    messagingSenderId: '75826378780',
    projectId: 'mybereal-f03e7',
    databaseURL: 'https://mybereal-f03e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybereal-f03e7.appspot.com',
    iosClientId: '75826378780-bj6ad29ussfvmakic5ap50961acp2v9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBeReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_AVcOdnTSgzDm5EqYkEs1DtWEbpI9J8',
    appId: '1:75826378780:ios:719076ebfc1325709f07d9',
    messagingSenderId: '75826378780',
    projectId: 'mybereal-f03e7',
    databaseURL: 'https://mybereal-f03e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mybereal-f03e7.appspot.com',
    iosClientId: '75826378780-qo9ffno7b35n90o4n38rm5kj56fl6379.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBeReal.RunnerTests',
  );
}
