name: Flutter CI

on:
  push:
    branches:
      - image_managing_v3
      - main
      - image_managing_v2

  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run Flutter Test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version:  3.13.6
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
